name: CI
on: [push, pull_request]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        
        - name: 'Login via Azure CLI'
          uses: Azure/docker-login@v1
          with:
              login-server: mitsha2.azurecr.io
              username: mitsha2
              password: 9OH9Lhl4ktdMBPpSAw/4dGkN7p0DglUV

        - run: |
            docker build . -t mitsha2.azurecr.io/test-app:${{ github.sha }}
            docker push mitsha2.azurecr.io/test-app:${{ github.sha }}

        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Deploy to Azure Container Instances'
          uses: azure/CLI@v1
          with: 
            azcliversion: 2.0.72
            inlineScript: |
              az container create --resource-group mitsha-test --name test-app --image mitsha2.azurecr.io/test-app:${{ github.sha }} --ports 80 8080 --dns-name-label test-app --registry-username mitsha2 --registry-password 9OH9Lhl4ktdMBPpSAw/4dGkN7p0DglUV