name: CI
on: [push, pull_request]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        
        - name: 'Login via Azure CLI'
          uses: Azure/docker-login@v1
          with:
              login-server: mitsha.azurecr.io
              username: ${{ SECRETS.REGISTRY_USERNAME }}
              password: ${{ SECRETS.REGISTRY_PASSWORD }}

        - run: |
            docker build . -t mitsha.azurecr.io/aciappdemo:${{ github.sha }}
            docker push mitsha.azurecr.io/aciappdemo:${{ github.sha }}

        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Deploy to Azure Container Instances'
          uses: azure/CLI@v1
          with: 
            azcliversion: 2.0.77
            inlineScript: |
              az container create --resource-group mitsha-test --name aciappdemo --image mitsha.azurecr.io/aciappdemo:${{ github.sha }} --ports 80 5777 --dns-name-label aciappdemo --registry-username 52d7cd83-e11a-4998-88cb-6e1394793634 --registry-password 09cd0421-e641-46c3-89dd-7d8855b88fbd
