name: CI
on: [push, pull_request]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        
        - name: 'Login via Azure CLI'
          uses: Azure/docker-login@v1
          with:
              login-server: mitsha.azurecr.io
              username: ${{ SECRETS.REGISTRY_USERNAME }}
              password: ${{ SECRETS.REGISTRY_PASSWORD }}

        - run: |
            docker build . -t mitsha.azurecr.io/aci-up-python-example:${{ github.sha }}
            docker push mitsha.azurecr.io/aci-up-python-example:${{ github.sha }}

        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            creds: ${{ SECRETS.AZURE_CREDENTIALS }}
            
        - name: 'Deploy to ACI using Action'
          uses: mitsha-microsoft/aci-create-action@v1

          with:
              resource-group: mitsha-test
              dns-name-label: action-test-aci
              image: nginx
              name: action-container-try
              location: 'central us'

