name: CI
on: [push, pull_request]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        
        - name: 'Login via Azure CLI'
          uses: Azure/docker-login@v1
          with:
              login-server: mitsha.azurecr.io
              username: ${{ SECRETS.REGISTRY_USERNAME }}
              password: ${{ SECRETS.REGISTRY_PASSWORD }}

        - run: |
            docker build . -t mitsha.azurecr.io/aci-up-python-example:${{ github.sha }}
            docker push mitsha.azurecr.io/aci-up-python-example:${{ github.sha }}

        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            creds: ${{ SECRETS.AZURE_CREDENTIALS }}
            
        - name: 'Deploy to ACI using Action'
          uses: mitsha-microsoft/aci-create-action@release-0.0.1

          with:
              resource-group: mitsha-test
              dns-name-label: action-test-aci
              image: mitsha.azurecr.io/aci-up-python-example:${{ github.sha }}
              registry-login-server: mitsha.azurecr.io
              name: action-container-try
              ports: '80 8080'
              registry-username: 'cb8b4991-a8a0-4412-b0be-50ac1cfce3e3'
              registry-passowrd: '55d807ae-b436-4b9e-837c-6195d26501a9'
              location: 'west us'

